version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/vocabulary_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    # image: mysql:5.7
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vocabulary_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db_data: