version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: wordbook-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordbook
      MYSQL_USER: wordbook_user
      MYSQL_PASSWORD: wordbook_pass
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  backend:
    build: ./backend
    container_name: wordbook-backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=wordbook_user
      - DB_PASSWORD=wordbook_pass
      - DB_NAME=wordbook
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: wordbook-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    # ホットリロードを有効にするためのボリュームマウント
    volumes:
      - ./frontend:/app
      - /app/node_modules