version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/wordbook
    volumes:
      - ./backend:/app

  db:
    # image: mysql:5.7
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordbook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: